### ISSUE TITLE
[4.20.13] First layer of spiralize no longer compensating flow

### ISSUE THREAD

**Issue by mattwn** [smartavionics/Cura#230]
**Application version**
Smartavionics Cura 4.20.13

**Platform**
Windows 10 64bit

**Printer**
Flsun Super Racer, also confirmed with Ender-3 profile, bug is observable in slicer and doesn't appear printer dependent. 

**Reproduction steps**
1. Load an solid hemisphere STL, oriented like a bowl
2. Selected the standard "Fine" profile.
3. Updates two slicer settings: "Spiralize" to True and "Minimum Layer Time" to 1 second (to equalize speed)

**Screenshot(s)**
![image](https://github.com/smartavionics/Cura/assets/95894900/1116486e-d242-4d10-8f0b-5c62443a7788)

**Actual results**
The first layer of the spiralized section (indicated by the red arrow in the screenshot at the top of the Z seam) did not show any reduction in flow. Actually printing this model results in a undesirable shelf of over extruded filament in this first layer.

**Expected results**
At one point, Smartavionics's Cura fork performed a gradient reduction in flow over the first layer of spiralize to compensate for the zero Z height of the starting point. This was a desirable feature that improved print quality at the transition into spiralize.

**Project file**
[FSR_Bowl.zip](https://github.com/smartavionics/Cura/files/11683442/FSR_Bowl.zip)

**Log file**
[cura.log](https://github.com/smartavionics/Cura/files/11683470/cura.log)

**Additional information**
I also tried this with the Ender-3 "Super Quality" profile that ships with Cura. Only changing the two referenced settings (spiralize and minimum layer time) plus enabling supports. The results were the same, there was no reduction in flow at the first layer of spiralize. 

I searched for other spiralize issues in the log before submitting this, I did not see another report of this issue.

Fact: Smartavionics's Cura is awesome.

**Comment by mattwn** [comment]
Just an update. I also inspected the gcode file and verified that the flow was not decreased at the first spiralize layer. The delta in E from line to line remained constant. I just wanted to confirm that the problem wasn't purely visual in the Cura flow preview.

Line 17082 ;LAYER:27 is the first spiralized layer.
[CE3_Bowl.zip](https://github.com/smartavionics/Cura/files/11683714/CE3_Bowl.zip)

**Comment by smartavionics** [comment]
Thanks for the report. I looked at the gcode in CE3_Bowl.gcode and it clearly shows the tapered flow at the beginning of the spiral. On that first spiralized layer, it starts with printing a normal height version of the wall and then it goes round again with, initially, a low flow rate which is then incremented along with Z so that by the time the outline is complete, Z matches the height of the next layer.

This first image is when the constant height part of the first spiralized layer is nearly finished. Note the flow value, that has been constant for all of the line so far:

![Screenshot_2023-06-08_12-44-51](https://github.com/smartavionics/Cura/assets/585618/c73e893b-866f-4f7e-a846-4d6d4f684b1e)

This next image is a little bit later, the constant height part is complete and it has started on the tapered part, note the flow value is less:

![Screenshot_2023-06-08_12-45-13](https://github.com/smartavionics/Cura/assets/585618/56ad7e31-2277-4d59-ad65-66ba503627f1)

And here it is a little bit further on, you can see the flow value has increased again but it still not the same as the value used for the non-tapered portion:

![Screenshot_2023-06-08_12-45-29](https://github.com/smartavionics/Cura/assets/585618/434ae87b-2c07-4df1-8aeb-44eec960829a)

The reported values for line width change as that is what controls the flow rate. The Z values don't change because of the known limitations of the Cura UI. What you should see is the Z values for the non-tapered portion being constant and then as the tapered portion is output, Z should increase. In the g-code, Z increases but not in the visualization.

Hope this helps.

**Comment by GregValiant** [comment]
Yep.
Flow rate per gcode line:
1.91992 >>> Line 6159 in ;LAYER:7
1.91949
0.50351
0.53029
0.55354
0.57622
0.60125
0.62681
0.64211
0.66860
0.68793
0.70711
0.73546
0.75622
0.77502
0.79751
0.82427
0.84181
0.86378
0.88812
0.91259
0.93785
0.96370
0.99101
1.00343
1.03286
1.05243
1.07179
1.10089
1.12161
1.14484
1.17569
1.19999
1.21203
1.23612
1.25992
1.28485
1.30869
1.33316
1.36393
1.38809
1.40851
1.42620
1.44471
1.47591
1.49340
1.51833
1.54416
1.56201
1.58318
1.60917
1.63183
1.65847
1.68352
1.71052
1.72514
1.75192
1.77378
1.79081
1.80791
1.84074
1.86532
1.89527
1.92083 >>> Line 6222

**Comment by mattwn** [comment]
I must not understand how it works then. 

The first 27 layers aren't really spiralized because of the supports. I thought that layers 0-26 were printed at a full layer height each and that the gradual stepping of Z didn't start until layer 27, in which case the flow compensation would be needed on that layer.

In the actual print you can see over extrusion on layer 27, right at the point where the supports stop and it starts printing a true spiral.

**Comment by smartavionics** [comment]
IMHO, spiral mode and supports are incompatible. The whole point of spiralization is that the nozzle traverses a single continuous path from the start of the spiral to the end. If the nozzle is jumping off every layer to print support then the result is always going to be ugly.

**Comment by mattwn** [comment]
100% agree. The first 26 layers should not and can not be spiralized because of the supports.

Spiralize isn't possible until layer 27. Thus flow compensation shouldn't occur till layer 27. 

That was my expectation anyway. But I accept that my understanding appears incorrect.

I will investigate using a cutting mesh to force spiralize not to start until layer 27, but I don't think spiralize is available as a per object setting.

**Comment by mattwn** [comment]
Closing this issue as this is not a bug and is the expected behavior as the flow compensation does occur on the first layer above the raft.

Print quality would still benefit from flow compensation on the first layer above the supports (as this is where spiralize truly starts). However this would be a new feature, not a bug fix.
