### ISSUE TITLE
5.x

### ISSUE THREAD

**Issue by jxer** [smartavionics/Cura#239]
why are you not moved over to the 5.x engine?

**Comment by smartavionics** [comment]
Hi,

I prefer to stay with Cura 4 because it's stable and simple and the build process supports Raspberry Pis. Plus the fact that I'm too lazy to port all my changes to the Cura 5 codebase. I want an easy life and that would be a lot of work for little gain. Of course, if anyone else wants to take my codebase and merge it with Cura 5, it's OK with me.

**Comment by jxer** [comment]
Alright thats fair, thank you, you can close
