### ISSUE TITLE
v20200208 - not slicing

### ISSUE THREAD

**Issue by amagr0** [smartavionics/Cura#42]
Application Version - CURA Master - v20200208
Platform - Win 10 Pro, 64 bit
Display Driver - NVIDIA GeForce 840M

Hello @smartavionics,

The latest version is not slicing, it starts, then slicing bar stops in the middle forever.
This stl with other version of Cura (not the previous) was sliced in less that 10 seconds.

![image](https://user-images.githubusercontent.com/12901952/74428950-eb95c500-4e51-11ea-8a54-2ac81a13abe5.png)

Thanks.

**Comment by smartavionics** [comment]
Can you please provide a project file that I can test. Thanks.

**Comment by amagr0** [comment]
[v20200208_not_slicing.zip](https://github.com/smartavionics/Cura/files/4197968/v20200208_not_slicing.zip)

**Comment by smartavionics** [comment]
Thanks. It slices fine on Linux. I'll fire up a Windows machine and try that.

**Comment by smartavionics** [comment]
It also slices fine on my Windows 10 machine.

Can you provide the cura.log and also the stderr.log files?

**Comment by amagr0** [comment]
[v20200208_not_slicing_logs.zip](https://github.com/smartavionics/Cura/files/4198061/v20200208_not_slicing_logs.zip)

**Comment by smartavionics** [comment]
It failed because it's missing a setting called bridge wall end boost. If you enable the bridge settings and set the expert setting visibility, you should see it like this here..

![Screenshot_2020-02-13_11-55-34](https://user-images.githubusercontent.com/585618/74433210-e471b580-4e57-11ea-9e44-e37d1cd95474.png)

It's visible on my Windows laptop, is it not visible for you?

**Comment by amagr0** [comment]
I don't have that option. All the parameters are visible.

![image](https://user-images.githubusercontent.com/12901952/74434873-3bc55500-4e5b-11ea-9385-8de486e534c4.png)

**Comment by smartavionics** [comment]
That's very odd because the setting is definitely in the release. Please remove the installation by completely deleting \program files\ultimaker cura master (or wherever it is installed) and try reinstalling. It looks like the file that contains the settings (resources\definitions\fdmprinter.def.json) has not been updated.

**Comment by amagr0** [comment]
I already uninstalled and deleted the Master files, but the problem remains (actually now I have other problems - configuration errors).

![image](https://user-images.githubusercontent.com/12901952/74450831-9e781a00-4e76-11ea-80b9-bc2b82cf3922.png)

**Comment by amagr0** [comment]
I found a solution by deleted the cache folder in \AppData\Local\cura\master

![image](https://user-images.githubusercontent.com/12901952/74451510-a84e4d00-4e77-11ea-8bee-d49a76edba97.png)
